common/models/Questionset.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "questionset".
 *
 * @property int $questionsetId
 * @property string $SetName
 * @property int $SubFullMark
 * @property int $ClassId
 * @property int $SubjetId
 * @property int $IsDelete 0=NotDeleted,1=Deleted
 * @property string|null $Ondate
 * @property string|null $UpdateDate
 */
class Questionset extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'questionset';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['SetName', 'ClassId', 'SubjetId', ], 'required'],
            [['ChapterId', 'ClassId', 'SubjetId', 'IsDelete', 'QuestionId'], 'integer'],
            [['Ondate', 'UpdateDate'], 'safe'],
            [['SetName'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'questionsetId' => 'Questionset ID',
            'SetName' => 'Exam/Set Name',
            'ChapterId' => 'Chapter Name',
            'QuestionId' => 'Questions',
            'ClassId' => 'Class Name',
            'SubjetId' => 'Subjet Name',
            'IsDelete' => 'Is Delete',
            'Ondate' => 'Ondate',
            'UpdateDate' => 'Update Date',
        ];
    }

    public function getClasses()
    {
        return $this->hasOne(Classes::className(), ['ClassId' => 'ClassId']);
    }

    public function getSubject()
    {
        return $this->hasOne(Subject::className(), ['SubjectId' => 'SubjetId']);
    }

    public function getChapter()
    {
        return $this->hasOne(Chapter::className(), ['ChapterId' => 'ChapterId']);
    }

    public function getQuestion()
    {
        return $this->hasOne(Question::className(), ['QuestionId' => 'QuestionId']);
    }

    public function getNoqsn($classid,$subjectid,$setname)
    {
        $qsncnt = Questionset::find()->where(['ClassId'=>$classid,'SubjetId'=>$subjectid,'SetName'=>$setname,'IsDelete'=>0])->count();
        return $qsncnt;
    }

    public function getExamenable()
    {
        return $this->hasOne(Examenable::className(), ['ClassId' => 'ClassId']);
    }

}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
		$this->layout = "login_main";
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $user = yii::$app->user->identity->RoleId;
            if($user == '3'){
                Yii::$app->user->logout();
                Yii::$app->session->setFlash('error', 'You are not an authorized user');
                return $this->goHome();
            }
            return $this->goBack();
        } else {
            $model->Password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\models\Tutorial;
use common\models\Userdetails;
use common\models\Subject;
use common\models\Classes;
use common\models\Chapter;
use common\models\Examenable;
use common\models\Questionset;
use yii\data\SqlDataProvider;
use common\models\Notice;
use common\models\Answer;
use yii\data\Pagination;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->redirect(['profile']);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */

    public function actionLogin()
    {
		$this->layout = "login";
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $user = yii::$app->user->identity->RoleId;
            if($user != '3'){
                Yii::$app->user->logout();
                Yii::$app->session->setFlash('error', 'You are not an authorized user');
                return $this->goHome();
            }
            return $this->goBack();
        } else {
            $model->Password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Displays Exam page.
     *
     * @return mixed
     */

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Thank you for registration. Please check your inbox for verification email.');
            return $this->goHome();
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail()) {
            if (Yii::$app->user->login($user)) {
                Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
                return $this->goHome();
            }
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }

    public function actionTutorial()
    {
        $uid = Yii::$app->user->identity->UserDetailsId;
        $user = Userdetails::find()->where(['UserDetailsId' => $uid,'IsDelete'=>0])->one();
        $classid = $user->Classid;
        if (isset(Yii::$app->request->post()['search'])) {
            $subjectid = Yii::$app->request->post()['SubjectId'];
            $chapterid = Yii::$app->request->post()['ChapterId'];
            $subname = Subject::find()->where(['SubjectId' => $subjectid,'IsDelete' => 0])->one();
            $chapname = Chapter::find()->where(['ChapterId' => $chapterid,'IsDelete' => 0])->one();
            $tutorial = Tutorial::find()
            ->where(['Classid'=>$classid,'SubjectId'=>$subjectid,'ChapterId'=>$chapterid,'IsDelete'=>0])
            ->all();
        }else{
            $tutorial =$subname = $chapname= '';
        }
        // var_dump($tutorial);die();
        return $this->render('studenttutorial', [
            'classid' => $classid,
            'tutorial' => $tutorial,
            'subname' => $subname,
            'chapname' => $chapname,
        ]);
    }

    public function actionProfile()
    {
        $userid = Yii::$app->user->identity->UserDetailsId;
        $profile = Userdetails::find()->where(['UserDetailsId' => $userid,'IsDelete'=>0])->one();
        
        
        return $this->render('profile', [
            'profile' => $profile
        ]);
    }

    public function actionSubjectlist($classid)
    {
        $subject = Subject::find()->where(['Classid' => $classid,'IsDelete' => 0])->asArray()->all();

        echo json_encode($subject);
    }

    public function actionChapterlist($subid)
    {
        $chapter = Chapter::find()->where(['SubjectId' => $subid,'IsDelete' => 0])->asArray()->all();

        echo json_encode($chapter);
    }

    public function actionExam()
    {
        $uid = Yii::$app->user->identity->UserDetailsId;
        $classid = Userdetails::find()->where(['UserDetailsId' => $uid,'IsDelete'=>0])->one();
        $questions = Examenable::find()->where(['ClassId' => $classid->Classid,'IsDelete'=>0])->all();
        return $this->render('exam', [
            'questions' => $questions
        ]);
    }

    public function actionExampanel($classid,$subjectid)
    {

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/exampanel.php
<?php
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\widgets\LinkPager;
/* @var $this yii\web\View */

$this->title = 'Exam';
?>
<style>
	.time{width:35px; border-radius:5px;min-width:35px; float:left; text-align:center;font-weight: bold;color: #e04949; padding:5px;box-shadow: 0 10px 15px -5px rgba(0, 0, 0, 0.5); background:#fff;}
	.qno{ width:50px; float:left; margin-right:10px;font-weight:600; border-radius:25px; padding:3px; text-align:center;background: #194175;color: #fff;}
</style>

<section class="content">
	<!-- Content Header (Page header) -->	  
	<div class="content-header">
		<div class="d-flex align-items-center justify-content-between">
			<div class="d-md-block d-none timers">
				<h3 class="page-title br-0">Remaing Times</h3>

				<ul style="list-style: none;padding: 0">
					<li style="list-style: none; float:left; display: inline-block; color:#fff; font-size: 25px;margin-right: 5px;"><i class="fa fa-clock-o"></i></li>
					<li style="list-style: none; float:left; display: inline-block; color:#fff;"><span id="hours" class="time"></span></li>
					<li style="list-style: none; float:left;display: inline-block;color:#fff;"><span style="float:left;margin:5px; margin-top:0px; font-size:20px;">:</span><span id="minutes" class="time"></span></li>
					<li style="list-style: none; float:left;display: inline-block;color:#fff;"><span style="float:left;margin:5px;margin-top:0px; font-size:20px;">:</span><span id="seconds" class="time"></span></li>
				</ul>
			</div>
			<div class="w-p60">

			</div>
			<div class="right-title w-170">
				<span class="subheader_daterange font-weight-600">
					<span class="subheader_daterange-label">
						<span class="subheader_daterange-title">Today:</span>
						<span class="subheader_daterange-date text-primary"><?=date('M d');?></span>
					</span>
					<a href="#" class="btn btn-rounded btn-sm btn-primary">
						<i class="fa fa-calendar"></i>
					</a>
				</span>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-12">

			<div class="box">


				<div class="box-header with-border">
					<h4 class="box-title">Questions</h4>
					<div class="box-controls pull-right">
						<div class="lookup lookup-circle lookup-right">
							<input type="text" name="s">
						</div>
					</div>
				</div>
				<div class="box-body">
					<div class="row">
						<div class="col-9" style="margin-top:10px;" id="demo">
							<?php
							$a =1;
							foreach ($models as $key => $value) {?>

								<p> <span class="qno"> Q.<?=$pages->offset+1?> </span> <?=$value->question->Questions?></p>
								<div class="col-12" style="padding-left:50px;">
									<input type="radio" id="lida<?=$a?>" name="ans<?=$a?>" onchange="submitanswer(this.value,<?=$a?>,<?=$timing->ExamId?>);" value="A" data-id="<?=$a?>">
									<label for="lida<?=$a?>"><?=$value->question->Ans_a?></label><br/>
									<input type="radio" id="lidb<?=$a?>" name="ans<?=$a?>" onchange="submitanswer(this.value,<?=$a?>,<?=$timing->ExamId?>);" value="B" data-id="<?=$a?>">
									<label for="lidb<?=$a?>"><?=$value->question->Ans_b?></label><br/>
									<input type="radio" id="lidc<?=$a?>" name="ans<?=$a?>" onchange="submitanswer(this.value,<?=$a?>,<?=$timing->ExamId?>);" value="C" data-id="<?=$a?>">
									<label for="lidc<?=$a?>"><?=$value->question->Ans_c?></label><br/>
									<input type="radio" id="lidd<?=$a?>" name="ans<?=$a?>" onchange="submitanswer(this.value,<?=$a?>,<?=$timing->ExamId?>);" value="D" data-id="<?=$a?>">
									<label for="lidd<?=$a?>"><?=$value->question->Ans_d?></label><br/>
								</div>
								<?php $a++;}
								echo LinkPager::widget([
								    'pagination' => $pages,
								]);
								?>
								<input type="hidden" id="endtimeforexam" value="<?=$endtimeforexam?>">		
							</div>
						<!-- <div class="col-3" style="padding-top:10px; background:#efefef;">
							<div style="width:100%; height:auto; float:left; margin-bottom:15px; border-bottom:1px solid #dedede;">
								<button type="button" class="btn btn-circle btn-success btn-xs mb-10">3</button> Answered
								<button type="button" class="btn btn-circle btn-info btn-xs mb-10">4</button> Marked<br/>
								<button type="button" class="btn btn-circle btn-default btn-xs mb-10">2</button> Not Visited
								<button type="button" class="btn btn-circle btn-danger btn-xs mb-10">1</button> Not Answer
							</div>
								<button type="button" class="btn btn-circle btn-success btn-sm mr-5 mb-10">1</button>
								<button type="button" class="btn btn-circle btn-success btn-sm mr-5 mb-10">2</button>
								<button type="button" class="btn btn-circle btn-info btn-sm mr-5 mb-10">3</button>
								<button type="button" class="btn btn-circle btn-success btn-sm mr-5 mb-10">4</button>
								<button type="button" class="btn btn-circle btn-info btn-sm mr-5 mb-10">5</button>
								<button type="button" class="btn btn-circle btn-success btn-sm mr-5 mb-10">6</button>
								<button type="button" class="btn btn-circle btn-danger btn-sm mr-5 mb-10">7</button>
								<button type="button" class="btn btn-circle btn-info btn-sm mr-5 mb-10">8</button>
								<button type="button" class="btn btn-circle btn-default btn-sm mr-5 mb-10">9</button>
								<button type="button" class="btn btn-circle btn-success btn-sm mr-5 mb-10">10</button>
							
							</div> -->
						</div>
					</div>	
					<div class="box-footer">
						<button type="button" class="btn  btn-info mb-5" style="float:right;">Next</button>
					</div>  



				</div>
			</div>
		</div>

	</section>

	<script >
		const second = 1000,
		minute = second * 60,
		hour = minute * 60,
		day = hour * 24;

		let countDown = '<?=$endtime;?>',
		x = setInterval(function() {    
			let now = new Date().getTime(),
			distance = countDown - now;
			document.getElementById('hours').innerText = Math.floor(distance / (hour)),
			document.getElementById('minutes').innerText = Math.floor((distance % (hour)) / (minute)),
			document.getElementById('seconds').innerText = Math.floor((distance % (minute)) / second);

		}, second)
		if(countDown < <?=strtotime(date('Y-m-d H:i:s'))*1000;?>){
			clearInterval(x);
			alert("Times up....");
			window.location.href = '<?=Url::toRoute(['site/index'])?>';
		}

		function submitanswer(value,qid,examid)
		{
			var endexam = $('#endtimeforexam').val();
			$.ajax({url:"<?=Url::toRoute(['site/answer-submit'])?>?ans="+value+"&qid="+qid+"&endexam="+endexam+"&examid="+examid,
				success:function(results)
				{
					if (!results) {
						alert("Oops....Session has Expired");
						window.location.href = window.location.href;
					}
                // alert(results);
            }
        });

		}
	</script>

frontend/views/site/studenttutorial.php
<?php
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
/* @var $this yii\web\View */

$this->title = 'Tutorial';
?>
<style>
.mainvideo{border:1px solid #dedede; padding:10px; min-height:250px; overflow:auto;}
.videobox{border:1px solid #dedede; }
</style>
<section class="content">

			<!-- Content Header (Page header) -->	  
			<div class="content-header">
				<div class="d-flex align-items-center justify-content-between">
					<div class="d-md-block d-none">
						<h3 class="page-title br-0">Tutorial</h3>
					</div>
					<div class="w-p60">
						
					</div>
					<div class="right-title w-170">
						<span class="subheader_daterange font-weight-600">
							<span class="subheader_daterange-label">
								<span class="subheader_daterange-title">Today:</span>
								<span class="subheader_daterange-date text-primary"><?=date('M d')?></span>
							</span>
							<a href="#" class="btn btn-rounded btn-sm btn-primary">
								<i class="fa fa-calendar"></i>
							</a>
						</span>
					</div>
				</div>
			</div>
			
<?php
    if (!$tutorial) {?>
	<div class="row">				
				
        <div class="col-lg-12 col-12" id="for-search">
		 <div class="box">
						<div class="box-header with-border">
						  <h4 class="box-title">Tutorial</h4>
						</div>
    <?php $form = ActiveForm::begin(); ?>
		<div class="box-body">
        <select id="subject-id" name="SubjectId" class="form-control" required onchange="chapterlist(this.value);">
            <option value="">Choose Subject</option>
        </select><br/>

        <select id="chapter-id" name="ChapterId" class="form-control" required>
            <option value="">Choose Chapter</option>
        </select>
		</div>
        <div class="box-footer">
            <?= Html::submitButton('<i class="ti-search"></i> Search', ['class' => 'btn btn-primary','name' => 'search']) ?>
        </div>
    <?php ActiveForm::end(); ?>
	</div>
		</div>
		</div>
   <?php }
?>

<?php 
if ($tutorial) {?>
<div class="row">
    <div class="col-lg-12 col-12" id="tut-res">
	 <div class="box">
						<div class="box-header with-border">
						  <h4 class="box-title"><?=$subname->SubjectName?><br/> <span style="color:#1d5f98; font-size:15px;"><?=$chapname->ChapterName?></span></h4>
						</div>
       
		<div class="box-body col-lg-12">
		<div class="row">
			<div  class="col-lg-6 " >
			<div class="mainvideo">
				<video id="mainvid" style="width:100%; height:200px;" controls controlsList="nodownload">
				  <source src="<?=Yii::getAlias('@storageUrl')."/tutorial/".$tutorial[0]->Video;?>" type="video/mp4">
				</video>
			 </div> 
			</div>
		
			<div class="col-lg-6" >
				<div class="mainvideo">
				 <p id="desc"><?=$tutorial[0]->Description?></p>
                 <a id="mainsubdoc" href="<?=Yii::getAlias('@storageUrl')."/tutorial/".$tutorial[0]->SubjectDoc?>" download><button class="btn btn-info btn-sm mb-5"><i class="fa fa-download"></i> Download PDF</button></a>
				</div>
			</div>
		</div>
		
		<div class="col-lg-12" style="margin-top:15px;">
		<div class="row">
			<h4 class="box-title" style="width:100%;">Upnext</h4>
                <?php
                foreach ($tutorial as $key => $value) {?>
                    <div class="col-lg-3"style="  " >
						<div class="videobox text-center">
						<h5 style="background: #1d5f98;color:#fff; text-align:center; padding:5px;"><?=$value->chapter->ChapterName?></h5>
                        <video width="100%" height="150" id="v<?=$key?>">
                          <source src="<?=Yii::getAlias('@storageUrl')."/tutorial/".$value->Video;?>" type="video/mp4">
                        </video>
                        <a id="subdoc" href="<?=Yii::getAlias('@storageUrl')."/tutorial/".$value->SubjectDoc?>" download><button class="btn btn-info btn-sm mb-5"><i class="fa fa-download"></i> Download PDF</button></a>
                        <input type="hidden" id="vdescription" value="<?=$value->Description?>">
                    </div>
                </div>
               <?php }
                ?>
				
		</div>
		</div>
	</div>
		
		
		</div>
		
		</div>
    </div>
	
<?php }?>
</section>
<script type="text/javascript">
<?php
if ($classid != '') {?>
    setTimeout(function() {
  subjectlist(<?=$classid?>);
}, 1000);
<?php }
?>
function subjectlist(value)
{
    $.ajax({url:"<?=Url::toRoute(['site/subjectlist'])?>?classid="+value,
            success:function(results)
            {
                if(results)
                {
                    $('#subject-id').html('<option value="">Select Subject</option>');
                    var subject=JSON.parse(results);
                    $.each(subject,function(key,value){
                        $('#subject-id').append('<option value="'+value.SubjectId+'">'+value.SubjectName+'</option>');
                    });
                    
                }
            }
        });
}

function chapterlist(value)
{
    $.ajax({url:"<?=Url::toRoute(['site/chapterlist'])?>?subid="+value,
            success:function(results)
            {
                if(results)
                {
                    $('#chapter-id').html('<option value="">Select Chapter</option>');
                    var chapter=JSON.parse(results);
                    $.each(chapter,function(key,value){
                        $('#chapter-id').append('<option value="'+value.ChapterId+'">'+value.ChapterName+'</option>');
                    });
                }
            }
        });
}
</script>
<?php
   $this->registerJs(
    "$('video').on('click',function(){
    var srcval=$(this).find('source').attr('src');
    var video = $('#mainvid').attr('src',srcval);
    video[0].play();
    $('#desc').html($(this).parent().find('#vdescription').val());
    var docval = $(this).parent().find('#subdoc').attr('href');
    $('#mainsubdoc').attr('href',docval);
    });"
    );
?>